<?php

declare(strict_types=1);

namespace GitiArts\Phase2\Tests;

use GitiArts\Phase2\Database\SchemaBuilder;
use PHPUnit\Framework\TestCase;

/**
 * Tests for the SchemaBuilder — verifies portability across SQLite and
 * PostgreSQL without actually running either engine.
 */
final class SchemaBuilderTest extends TestCase
{
    public function test_generates_sqlite_create_table(): void
    {
        $statements = SchemaBuilder::table('test_table')
            ->uuid('id')
            ->string('name')
            ->datetime('created_at')
            ->toSql('sqlite');

        self::assertNotEmpty($statements);
        self::assertStringStartsWith('CREATE TABLE IF NOT EXISTS test_table', $statements[0]);
        self::assertStringContainsString('id TEXT', $statements[0]);
        self::assertStringContainsString('name TEXT NOT NULL', $statements[0]);
        self::assertStringContainsString('created_at TEXT NOT NULL', $statements[0]);
    }

    public function test_generates_postgres_create_table(): void
    {
        $statements = SchemaBuilder::table('test_table')
            ->uuid('id')
            ->string('name')
            ->datetime('created_at')
            ->toSql('postgres');

        self::assertStringContainsString('id UUID', $statements[0]);
        self::assertStringContainsString('name TEXT NOT NULL', $statements[0]);
        self::assertStringContainsString('created_at TIMESTAMP NOT NULL', $statements[0]);
    }

    public function test_boolean_maps_correctly_per_driver(): void
    {
        $sqlite = SchemaBuilder::table('t')->boolean('active')->toSql('sqlite');
        self::assertStringContainsString('active INTEGER NOT NULL', $sqlite[0]);

        $pg = SchemaBuilder::table('t')->boolean('active')->toSql('postgres');
        self::assertStringContainsString('active BOOLEAN NOT NULL', $pg[0]);
    }

    public function test_json_maps_to_jsonb_in_postgres(): void
    {
        $pg = SchemaBuilder::table('t')->json('metadata')->toSql('postgres');
        self::assertStringContainsString('metadata JSONB', $pg[0]);
    }

    public function test_auto_increment_primary_key(): void
    {
        $sqlite = SchemaBuilder::table('t')->bigInt('id', true)->toSql('sqlite');
        self::assertStringContainsString('PRIMARY KEY AUTOINCREMENT', $sqlite[0]);

        $pg = SchemaBuilder::table('t')->bigInt('id', true)->toSql('postgres');
        self::assertStringContainsString('GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', $pg[0]);
    }

    public function test_index_statements_generated(): void
    {
        $statements = SchemaBuilder::table('orders')
            ->uuid('id')
            ->string('status')
            ->index('status')
            ->toSql('sqlite');

        $hasIndexStmt = false;
        foreach ($statements as $s) {
            if (str_starts_with($s, 'CREATE INDEX')) {
                $hasIndexStmt = true;
                self::assertStringContainsString('orders_idx_status', $s);
            }
        }
        self::assertTrue($hasIndexStmt, 'Expected at least one CREATE INDEX statement');
    }

    public function test_unique_constraint_generates_unique_index(): void
    {
        $statements = SchemaBuilder::table('users')
            ->uuid('id')
            ->string('mobile')
            ->unique('mobile')
            ->toSql('sqlite');

        $hasUnique = false;
        foreach ($statements as $s) {
            if (str_starts_with($s, 'CREATE UNIQUE INDEX')) {
                $hasUnique = true;
            }
        }
        self::assertTrue($hasUnique);
    }

    public function test_nullable_column_omits_not_null(): void
    {
        $statements = SchemaBuilder::table('t')
            ->string('optional_field')->nullable()
            ->toSql('sqlite');

        self::assertStringNotContainsString('NOT NULL', $statements[0]);
    }
}
